### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by teogor**

### CODE REVIEW

**Comment by teogor** [comment]
test

**Comment by teogor** [comment]
try

**Comment by teogor** [comment]
try

**Comment by teogor** [comment]
try

**Comment by teogor** [comment]
s

**Comment by teogor** [comment]
attempt

**Comment by teogor** [comment]
Hello, man!

**Comment by teogor** [comment]
try?

**Comment by teogor** [comment]
there

**Comment by teogor** [comment]
and now?

**Comment by teogor** [comment]
test

**Comment by teogor** [comment]
what

**Comment by teogor** [comment]
gs

**Comment by teogor** [comment]
and now

**Comment by teogor** [comment]
there we go

**Comment by teogor** [comment]
And?

**Comment by teogor** [comment]
th

**Comment by teogor** [comment]
ad

**Comment by teogor** [comment]
and now

**Comment by teogor** [comment]
now

**Comment by teogor** [comment]
che

**Comment by teogor** [comment]
and?

**Comment by teogor** [comment]
bew?

**Comment by TeodorHMX1** [comment]
attempt

**Pull request merged**
