### PR TITLE
Update zeobot-contributors.src

### PR DESCRIPTION
**Pull request by teogor**

### CODE REVIEW

**Comment by teogor** [comment]
@zeobot enforce branch merge

**Comment by TeodorHMX1** [comment]
@zeobot override branch merge

**Comment by TeodorHMX1** [comment]
@zeobot enforce branch merge

**Comment by TeodorHMX1** [comment]
@zeobot enforce branch merge

**Comment by TeodorHMX1** [comment]
@zeobot override branch merge

**Comment by teogor** [comment]
@zeobot override branch merge

**Comment by teogor** [comment]
@zeobot enforce branch merge

**Comment by teogor** [comment]
@zeobot enforce branch merge

**Comment by TeodorHMX1** [comment]
@zeobot enforce branch merge

**Comment by TeodorHMX1** [comment]
@zeobot override branch merge

**Comment by TeodorHMX1** [comment]
@zeobot enforce branch merge

**Comment by teogor** [comment]
@zeobot enforce branch merge

**Comment by teogor** [comment]
@zeobot enforce branch merge

**Comment by teogor** [comment]
@zeobot enforce branch merge

**Comment by TeodorHMX1** [comment]
@zeobot enforce branch merge

**Comment by teogor** [comment]
@zeobot enforce branch merge

**Comment by TeodorHMX1** [comment]
@zeobot enforce branch merge

**Comment by TeodorHMX1** [comment]
@zeobot enforce branch merge

**Comment by TeodorHMX1** [comment]
@zeobot enforce branch merge

**Comment by TeodorHMX1** [comment]
@zeobot enforce branch merge

**Comment by TeodorHMX1** [comment]
@zeobot enforce branch merge

**Comment by TeodorHMX1** [comment]
@zeobot enforce branch merge

**Comment by TeodorHMX1** [comment]
@zeobot override branch merge

**Comment by TeodorHMX1** [comment]
@zeobot override branch merge

**Comment by teogor** [comment]
@zeobot enforce branch merge

**Comment by TeodorHMX1** [comment]
@zeobot enforce branch merge

**Comment by teogor** [comment]
@zeobot set bip

**Comment by teogor** [comment]
@zeobot enforce branch merge

**Comment by TeodorHMX1** [comment]
@zeobot enforce branch merge

**Comment by TeodorHMX1** [comment]
@zeobot set bip

**Comment by TeodorHMX1** [comment]
@zeobot d eletebip

**Comment by TeodorHMX1** [comment]
@zeobot delete bip

**Comment by teogor** [comment]
@zeobot delete branch

**Pull request closed without merging**
