### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by teogor**

### CODE REVIEW

**Comment by teogor** [comment]
@zeobot enforce branch merge

**Comment by teogor** [comment]
@zeobot enforce branch merge

**Comment by TeodorHMX1** [comment]
@zeobot enforce branch merge

**Comment by teogor** [comment]
@zeobot enforce branch merge

**Comment by teogor** [comment]
@zeobot enforce branch merge

**Comment by teogor** [comment]
@zeobot enforce branch merge

**Comment by teogor** [comment]
@zeobot enforce branch merge

**Comment by teogor** [comment]
@zeobot override branch merge

**Comment by teogor** [comment]
@zeobot enforce branch merge

**Comment by teogor** [comment]
@zeobot enforce branch merge

**Comment by teogor** [comment]
@zeobot override branch merge

**Comment by teogor** [comment]
@zeobot enforce branch merge

**Comment by TeodorHMX1** [comment]
@zeobot enforce branch merge

**Comment by teogor** [comment]
@zeobot enforce branch merge

**Comment by teogor** [comment]
@zeobot enforce branch merge

**Comment by teogor** [comment]
@zeobot enforce branch merge

**Comment by teogor** [comment]
@zeobot enforce branch merge

**Comment by teogor** [comment]
@zeobot enforce branch merge

**Comment by teogor** [comment]
@zeobot enforce branch merge

**Comment by teogor** [comment]
@zeobot enforce branch merge

**Comment by teogor** [comment]
@zeobot enforce branch merge

**Comment by teogor** [comment]
@zeobot enforce branch merge

**Comment by teogor** [comment]
@zeobot enable stuff

**Comment by teogor** [comment]
@zeobot check

**Comment by teogor** [comment]
@zeobot close

**Comment by teogor** [comment]
@zeobot close this

**Comment by teogor** [comment]
Signed-off-by Teogor <teogor@zeoflow.com>

**Comment by teogor** [comment]
Signed-off-by: Teodor <teogor@zeoflow.com>

**Comment by teogor** [comment]
@zeobot enforce branch merge

**Comment by teogor** [comment]
@zeobot set ebm, lc to pass

**Comment by teogor** [comment]
@zeobot set ebm, lc to pass

**Comment by teogor** [comment]
@zeobot set ebm, ccs to pass

**Comment by teogor** [comment]
@zeobot set ebm, ccs to pass

**Comment by teogor** [comment]
@zeobot set ebm, ccs to pass

**Comment by teogor** [comment]
@zeobot set ebm, ccs to fail

**Comment by TeodorHMX1** [comment]
@zeobot set ebm, ccs, lc, bip to fail

**Comment by TeodorHMX1** [comment]
@zeobot set ebm, ccs, lc, bip to pass

**Comment by TeodorHMX1** [comment]
@zeobot set ebm, ccs, lc, bip to pass

**Comment by TeodorHMX1** [comment]
@zeobot set ebm, ccs, lc, bip to pass

**Comment by TeodorHMX1** [comment]
@zeobot set ebm, ccs, lc, bip to fail

**Comment by TeodorHMX1** [comment]
@zeobot set ebm, ccs, lc, bip to pass

**Comment by TeodorHMX1** [comment]
@zeobot set ebm, ccs, lc, bip to pass

**Comment by TeodorHMX1** [comment]
@zeobot set ccs to afil

**Comment by TeodorHMX1** [comment]
@zeobot set ccs to fail

**Comment by TeodorHMX1** [comment]
@zeobot set ccs to fail

**Comment by TeodorHMX1** [comment]
@zeobot set ccs to fail

**Comment by TeodorHMX1** [comment]
@zeobot set ccs to fail

**Comment by TeodorHMX1** [comment]
@zeobot set ccs to pass

**Comment by TeodorHMX1** [comment]
@zeobot set ccs to fail

**Comment by teogor** [comment]
@zeobot set ccs to pass

**Comment by TeodorHMX1** [comment]
@zeobot close pr

**Comment by TeodorHMX1** [comment]
@zeobot close pr

**Comment by TeodorHMX1** [comment]
@zeobot close pr

**Comment by TeodorHMX1** [comment]
@zeobot close pr

**Comment by TeodorHMX1** [comment]
@zeobot close pr

**Comment by TeodorHMX1** [comment]
@zeobot do this

**Comment by TeodorHMX1** [comment]
@zeobot what

**Comment by TeodorHMX1** [comment]
@zeobot close

**Comment by TeodorHMX1** [comment]
@zeobot set what

**Comment by TeodorHMX1** [comment]
@zeobot set this to

**Comment by TeodorHMX1** [comment]
@zeobot set ccs to pass

**Comment by TeodorHMX1** [comment]
@Zeobot close what

**Comment by TeodorHMX1** [comment]
@zeobot close

**Comment by TeodorHMX1** [comment]
@zeobot close wh

**Comment by TeodorHMX1** [comment]
@zeobot close this

**Comment by TeodorHMX1** [comment]
@zeobot close this and that

**Comment by TeodorHMX1** [comment]
@zeobot close bfhkd rgt h

**Comment by TeodorHMX1** [comment]
@zeobot close pr

**Comment by TeodorHMX1** [comment]
@zeobot close pr now

**Comment by TeodorHMX1** [comment]
@zeobot close this pr

**Comment by TeodorHMX1** [comment]
@zeobot close this pr and open this pr

**Comment by TeodorHMX1** [comment]
@zeobot close what

**Comment by TeodorHMX1** [comment]
@zeobot close pr

**Comment by TeodorHMX1** [comment]
@zeobot close pr

**Comment by TeodorHMX1** [comment]
@zeobot open pr

**Comment by TeodorHMX1** [comment]
@zeobot set cca and ebm to pass

**Comment by TeodorHMX1** [comment]
@zeobot set ccs to pass

**Comment by TeodorHMX1** [comment]
@zeobot set ebm to fail

**Comment by TeodorHMX1** [comment]
@zeobot set as bip

**Comment by TeodorHMX1** [comment]
@zeobot set as done

**Comment by TeodorHMX1** [comment]
@zeobot set bip, ccs, ebm to pass

**Comment by TeodorHMX1** [comment]
@zeobot delete bip

**Comment by TeodorHMX1** [comment]
@zeobot delete br

**Comment by TeodorHMX1** [comment]
@zeobot open branch

**Comment by TeodorHMX1** [comment]
@zeobot do ts

**Comment by TeodorHMX1** [comment]
@zeobot open br

**Comment by TeodorHMX1** [comment]
@zeobot open pr

**Comment by TeodorHMX1** [comment]
@zeobot open br

**Comment by TeodorHMX1** [comment]
@zeobot open br

**Comment by TeodorHMX1** [comment]
@zeobot open br

**Comment by teogor** [comment]
@zeobot attempt somehting

**Comment by TeodorHMX1** [comment]
@zeobot create pr

**Comment by TeodorHMX1** [comment]
@zeobot open pr

**Comment by TeodorHMX1** [comment]
@zeobot open br

**Pull request closed without merging**
